# Generated by Django 2.2.2 on 2019-06-21 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.TextField(default='Unknown Seller')),
                ('product_name', models.TextField(default='Unknown Name')),
                ('product_price_AUD', models.FloatField(default=0)),
                ('product_price_TWD', models.FloatField(default=0)),
                ('pre_selling_price_AUD', models.FloatField(default=0)),
                ('pre_selling_price_TWD', models.FloatField(default=0)),
                ('actual_selling_price_AUD', models.FloatField(default=0)),
                ('actual_selling_price_TWD', models.FloatField(default=0)),
                ('description', models.TextField(default='Unknown Description')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'product',
            },
        ),
    ]
